buildscript {
    ext {
        compose_version = '1.5.1'
        detekt_version = '1.23.6'
    }
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.7.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:2.0.21"
        classpath "org.jetbrains.kotlin:compose-compiler-gradle-plugin:2.0.21"
        classpath 'com.google.gms:google-services:4.4.1'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:3.0.1'
        classpath "io.gitlab.arturbosch.detekt:detekt-gradle-plugin:$detekt_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
    // Redirect build directory outside OneDrive to prevent file-locking and snapshotting errors
    buildDir = "C:/android-builds/The-Greggory-Client-Portal/${project.name}"
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
