# PRODUCTION SIGNING DETAILS
# Replace these with your actual passwords after creating your Keystore in Android Studio
KEYSTORE_PATH=C:/Users/Lydia mwanza/OneDrive/Desktop/greggory_production_key.jks
KEYSTORE_PASSWORD=greggory2024
KEY_ALIAS=greggory_alias
KEY_PASSWORD=greggory2024
