# PRODUCTION SIGNING DETAILS
# Replace these with your actual passwords after creating your Keystore in Android Studio
KEYSTORE_PATH=YOUR_KEYSTORE_FILE_PATH_HERE
KEYSTORE_PASSWORD=YOUR_KEYSTORE_PASSWORD_HERE
KEY_ALIAS=YOUR_KEY_ALIAS_HERE
KEY_PASSWORD=YOUR_KEY_PASSWORD_HERE
